name: Build SuperMario Tweaker Magisk Module

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to build (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build:
    name: Build SuperMario Tweaker Magisk Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create SuperMario Tweaker Zip
        run: |
          zip -r SuperMarioTweaker-${{ github.event.inputs.tag_name }}.zip . -x ".git*" -x ".github*" -x "README.md" -x "update.json" -x "UPDATE.md" -x "assets"
    
      - name: Create a tag
        run: |
          git tag ${{ github.event.inputs.tag_name }}
          git push origin ${{ github.event.inputs.tag_name }}

      - name: Upload SuperMario Tweaker to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            SuperMarioTweaker-${{ github.event.inputs.tag_name }}.zip
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: SuperMario Tweaker 
          body: |
            SuperMario Tweaker${{ github.event.inputs.tag_name }}